export const HTTP_FORGE_DEFAULT_CREDENTIALS = 'same-origin';
export const HTTP_FORGE_DEFAULT_RETRY_LENGTH = 5;
export const HTTP_FORGE_DEFAULT_TIMEOUT_LENGTH = 8000;
export const HTTP_FORGE_DEFAULT_RETRY_BACKOFF_FACTOR = 0.3;
